In [4]:
import gzip
import json
import os
import numpy as np
import pandas as pd

In [5]:
def load_data(file_name):
    data = []
    with gzip.open(file_name) as f:
        for l in f:
            d = json.loads(l.strip())
            new_d= {k: d[k] for k in ('user_id', 'book_id', 'review_id', 'rating', 'review_text')}
            data.append(new_d)
    return data

def load_data2(file_name):
    data = []
    with gzip.open(file_name) as f:
        for l in f:
            d = json.loads(l.strip())
            new_d ={k: d[k] for k in ('isbn', 'text_reviews_count', 'average_rating', 'description', 'link', 'url', 'image_url' ,'book_id','ratings_count','title')}
            data.append(new_d)
    return data

In [ ]:
# {'isbn': '9796869055',
#  'text_reviews_count': '3',
#  'average_rating': '3.11',
#  'description': '',
#  'link': 'https://www.goodreads.com/book/show/1049394.Doktor_Plimin',
#  'isbn13': '9789796869053',
#  'url': 'https://www.goodreads.com/book/show/1049394.Doktor_Plimin',
#  'image_url': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
#  'book_id': '1049394',
#  'ratings_count': '19',
#  'title': 'Doktor Plimin: Kumpulan Cerpen'
# }

In [6]:
DIR ='C:/Users/noura/Downloads'

In [7]:
records = load_data(os.path.join(DIR, 'goodreads_reviews_dedup.json.gz'))

In [10]:
books = load_data2(os.path.join(DIR, 'goodreads_books.json.gz'))

In [13]:
print('Number of records: {}'.format(len(records)))
print('sample random record')
display(np.random.choice(records))
# Number of records: 15,739,967

Number of records: 15739967
sample random record

{'user_id': 'b44ce98f6cd7ec8172de2356f94c857f',
 'book_id': '752461',
 'review_id': 'ada7f4a89ba1fe06ea5d1e2b13aaf927',
 'rating': 5,
 'review_text': 'This was the first book I had read by Abnett. I really enjoyed the writing style, the evocative background of the WH40K universe and above all the story. The characters are very human, and believable, with strengths, weaknesses and flaws, and individual personality.',
 'date_added': 'Wed Jul 04 03:33:09 -0700 2012',
 'date_updated': 'Wed Jul 04 03:35:34 -0700 2012',
 'read_at': 'Sat Jan 01 00:00:00 -0800 2011',
 'started_at': '',
 'n_votes': 0,
 'n_comments': 0}

In [5]:
print('Number of records: {}'.format(len(books)))
print('sample random book record')
display(np.random.choice(books))

Number of records: 2360655
sample random book record

{'isbn': '9796869055',
 'text_reviews_count': '3',
 'series': [],
 'country_code': 'US',
 'language_code': 'ind',
 'popular_shelves': [{'count': '21', 'name': 'to-read'},
  {'count': '2', 'name': 'currently-reading'},
  {'count': '1', 'name': 'owned'},
  {'count': '1', 'name': 'kumpulan-cerpen'},
  {'count': '1', 'name': 'koleksi-saya'},
  {'count': '1', 'name': 'punya-tinggalbaca'},
  {'count': '1', 'name': 'buku-pengen-beli'}],
 'asin': '',
 'is_ebook': 'false',
 'average_rating': '3.11',
 'kindle_asin': '',
 'similar_books': [],
 'description': '',
 'format': 'Paperback',
 'link': 'https://www.goodreads.com/book/show/1049394.Doktor_Plimin',
 'authors': [{'author_id': '626036', 'role': ''}],
 'publisher': '',
 'num_pages': '109',
 'publication_day': '',
 'isbn13': '9789796869053',
 'publication_month': '',
 'edition_information': '',
 'publication_year': '',
 'url': 'https://www.goodreads.com/book/show/1049394.Doktor_Plimin',
 'image_url': 'https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png',
 'book_id': '1049394',
 'ratings_count': '19',
 'work_id': '1035845',
 'title': 'Doktor Plimin: Kumpulan Cerpen',
 'title_without_series': 'Doktor Plimin: Kumpulan Cerpen'}

In [8]:
# convert the read json data into a pandas dataframe
df = pd.DataFrame.from_records(records[0:10000000])
df.head()

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,24375664,5cd416f3efc3f944fce4ce2db2290d5e,5,Mind blowingly cool. Best science fiction I've...,Fri Aug 25 13:55:02 -0700 2017,Mon Oct 09 08:55:59 -0700 2017,Sat Oct 07 00:00:00 -0700 2017,Sat Aug 26 00:00:00 -0700 2017,16,0
1,8842281e1d1347389f2ab93d60773d4d,18245960,dfdbb7b0eb5a7e4c26d59a937e2e5feb,5,This is a special book. It started slow for ab...,Sun Jul 30 07:44:10 -0700 2017,Wed Aug 30 00:00:26 -0700 2017,Sat Aug 26 12:05:52 -0700 2017,Tue Aug 15 13:23:18 -0700 2017,28,1
2,8842281e1d1347389f2ab93d60773d4d,6392944,5e212a62bced17b4dbe41150e5bb9037,3,I haven't read a fun mystery book in a while a...,Mon Jul 24 02:48:17 -0700 2017,Sun Jul 30 09:28:03 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,Mon Jul 24 00:00:00 -0700 2017,6,0
3,8842281e1d1347389f2ab93d60773d4d,22078596,fdd13cad0695656be99828cd75d6eb73,4,"Fun, fast paced, and disturbing tale of murder...",Mon Jul 24 02:33:09 -0700 2017,Sun Jul 30 10:23:54 -0700 2017,Sun Jul 30 15:42:05 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,22,4
4,8842281e1d1347389f2ab93d60773d4d,6644782,bd0df91c9d918c0e433b9ab3a9a5c451,4,A fun book that gives you a sense of living in...,Mon Jul 24 02:28:14 -0700 2017,Thu Aug 24 00:07:20 -0700 2017,Sat Aug 05 00:00:00 -0700 2017,Sun Jul 30 00:00:00 -0700 2017,8,0

In [9]:
# save the dataframe to a csv file
df.to_csv('goodreads_reviews_dedup2.csv', index=False)

In [10]:
df.head()

,user_id,book_id,review_id,rating,review_text,date_added,date_updated,read_at,started_at,n_votes,n_comments
0,8842281e1d1347389f2ab93d60773d4d,24375664,5cd416f3efc3f944fce4ce2db2290d5e,5,Mind blowingly cool. Best science fiction I've...,Fri Aug 25 13:55:02 -0700 2017,Mon Oct 09 08:55:59 -0700 2017,Sat Oct 07 00:00:00 -0700 2017,Sat Aug 26 00:00:00 -0700 2017,16,0
1,8842281e1d1347389f2ab93d60773d4d,18245960,dfdbb7b0eb5a7e4c26d59a937e2e5feb,5,This is a special book. It started slow for ab...,Sun Jul 30 07:44:10 -0700 2017,Wed Aug 30 00:00:26 -0700 2017,Sat Aug 26 12:05:52 -0700 2017,Tue Aug 15 13:23:18 -0700 2017,28,1
2,8842281e1d1347389f2ab93d60773d4d,6392944,5e212a62bced17b4dbe41150e5bb9037,3,I haven't read a fun mystery book in a while a...,Mon Jul 24 02:48:17 -0700 2017,Sun Jul 30 09:28:03 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,Mon Jul 24 00:00:00 -0700 2017,6,0
3,8842281e1d1347389f2ab93d60773d4d,22078596,fdd13cad0695656be99828cd75d6eb73,4,"Fun, fast paced, and disturbing tale of murder...",Mon Jul 24 02:33:09 -0700 2017,Sun Jul 30 10:23:54 -0700 2017,Sun Jul 30 15:42:05 -0700 2017,Tue Jul 25 00:00:00 -0700 2017,22,4
4,8842281e1d1347389f2ab93d60773d4d,6644782,bd0df91c9d918c0e433b9ab3a9a5c451,4,A fun book that gives you a sense of living in...,Mon Jul 24 02:28:14 -0700 2017,Thu Aug 24 00:07:20 -0700 2017,Sat Aug 05 00:00:00 -0700 2017,Sun Jul 30 00:00:00 -0700 2017,8,0

In [11]:
# convert the read json data into a pandas dataframe
df_books = pd.DataFrame.from_records(books[0:2000000])
df_books.head()

,isbn,text_reviews_count,average_rating,description,link,url,image_url,book_id,ratings_count,title
0,0312853122,1,4.00,,https://www.goodreads.com/book/show/5333265-w-...,https://www.goodreads.com/book/show/5333265-w-...,https://images.gr-assets.com/books/1310220028m...,5333265,3,W.C. Fields: A Life on Film
1,0743509986,6,3.23,"Anita Diamant's international bestseller ""The ...",https://www.goodreads.com/book/show/1333909.Go...,https://www.goodreads.com/book/show/1333909.Go...,https://s.gr-assets.com/assets/nophoto/book/11...,1333909,10,Good Harbor
2,,7,4.03,Omnibus book club edition containing the Ladie...,https://www.goodreads.com/book/show/7327624-th...,https://www.goodreads.com/book/show/7327624-th...,https://images.gr-assets.com/books/1304100136m...,7327624,140,"The Unschooled Wizard (Sun Wolf and Starhawk, ..."
3,0743294297,3282,3.49,Addie Downs and Valerie Adler were eight when ...,https://www.goodreads.com/book/show/6066819-be...,https://www.goodreads.com/book/show/6066819-be...,https://s.gr-assets.com/assets/nophoto/book/11...,6066819,51184,Best Friends Forever
4,0850308712,5,3.40,,https://www.goodreads.com/book/show/287140.Run...,https://www.goodreads.com/book/show/287140.Run...,https://images.gr-assets.com/books/1413219371m...,287140,15,Runic Astrology: Starcraft and Timekeeping in ...

In [12]:
# save the dataframe to a csv file
df_books.to_csv('goodreads_books.csv', index=False)
# s3 folder
#s3://aws-logs-474588691358-us-east-1/elasticmapreduce/